version: '3.3'

services:
  # --- Application Service ---
  app:
    build: .
    container_name: restaurant_app
    restart: always
    ports:
      - "5000:5000" # Backup Direct Access
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis
    networks:
      - app-network

  # --- Nginx Web Server (Reverse Proxy) ---
  nginx:
    image: nginx:alpine
    container_name: restaurant_nginx
    restart: always
    ports:
      - "80:80" # Public Port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  # --- Redis Cache Service ---
  redis:
    image: redis:alpine
    container_name: restaurant_redis
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
